version: "3.9"
services:
  client:
    build:
      context: ./food_delivery_app_ui
    ports:
      - "3000:3000"
    volumes:
      - ./food_delivery_app_ui:/food_delivery_app_ui
    image: client:client
    container_name: react_container
    command: npm start
 
  mssql:
    build: ./food_delivery_app_db
    container_name: db
    ports:
      - "1433:1433"
 
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./food_delivery_app_backend
      dockerfile: ./food_delivery_app_api/Dockerfile
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      ASPNETCORE_URLS: "http://+80;https://+443"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: 'true'
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./food_delivery_app_backend/food_delivery_app_api:/food_delivery_app_api
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https
      - ${APPDATA}/Microsoft/UseSecrets:/root/.microsoft/usersecrects
      - ~/.aspnet/https:/https
    container_name: api
    depends_on:
      - mssql